// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto/example.proto

package example

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/protobuf/types"
	math "math"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Example struct {
	CurrentTime          *time.Time `protobuf:"bytes,1,opt,name=current_time,json=currentTime,proto3,stdtime" json:"current_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Example) Reset()         { *m = Example{} }
func (m *Example) String() string { return proto.CompactTextString(m) }
func (*Example) ProtoMessage()    {}
func (*Example) Descriptor() ([]byte, []int) {
	return fileDescriptor_45cce4fba0c1b108, []int{0}
}
func (m *Example) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Example.Unmarshal(m, b)
}
func (m *Example) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Example.Marshal(b, m, deterministic)
}
func (m *Example) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Example.Merge(m, src)
}
func (m *Example) XXX_Size() int {
	return xxx_messageInfo_Example.Size(m)
}
func (m *Example) XXX_DiscardUnknown() {
	xxx_messageInfo_Example.DiscardUnknown(m)
}

var xxx_messageInfo_Example proto.InternalMessageInfo

func (m *Example) GetCurrentTime() *time.Time {
	if m != nil {
		return m.CurrentTime
	}
	return nil
}

type ExampleRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExampleRequest) Reset()         { *m = ExampleRequest{} }
func (m *ExampleRequest) String() string { return proto.CompactTextString(m) }
func (*ExampleRequest) ProtoMessage()    {}
func (*ExampleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_45cce4fba0c1b108, []int{1}
}
func (m *ExampleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExampleRequest.Unmarshal(m, b)
}
func (m *ExampleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExampleRequest.Marshal(b, m, deterministic)
}
func (m *ExampleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExampleRequest.Merge(m, src)
}
func (m *ExampleRequest) XXX_Size() int {
	return xxx_messageInfo_ExampleRequest.Size(m)
}
func (m *ExampleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExampleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExampleRequest proto.InternalMessageInfo

type ExampleResponse struct {
	Example              *Example `protobuf:"bytes,1,opt,name=example,proto3" json:"example,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExampleResponse) Reset()         { *m = ExampleResponse{} }
func (m *ExampleResponse) String() string { return proto.CompactTextString(m) }
func (*ExampleResponse) ProtoMessage()    {}
func (*ExampleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_45cce4fba0c1b108, []int{2}
}
func (m *ExampleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExampleResponse.Unmarshal(m, b)
}
func (m *ExampleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExampleResponse.Marshal(b, m, deterministic)
}
func (m *ExampleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExampleResponse.Merge(m, src)
}
func (m *ExampleResponse) XXX_Size() int {
	return xxx_messageInfo_ExampleResponse.Size(m)
}
func (m *ExampleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExampleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExampleResponse proto.InternalMessageInfo

func (m *ExampleResponse) GetExample() *Example {
	if m != nil {
		return m.Example
	}
	return nil
}

func init() {
	proto.RegisterType((*Example)(nil), "example.Example")
	proto.RegisterType((*ExampleRequest)(nil), "example.ExampleRequest")
	proto.RegisterType((*ExampleResponse)(nil), "example.ExampleResponse")
}

func init() { proto.RegisterFile("proto/example.proto", fileDescriptor_45cce4fba0c1b108) }

var fileDescriptor_45cce4fba0c1b108 = []byte{
	// 228 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0xad, 0x48, 0xcc, 0x2d, 0xc8, 0x49, 0xd5, 0x03, 0xf3, 0x84, 0xd8, 0xa1, 0x5c,
	0x29, 0xf9, 0xf4, 0xfc, 0xfc, 0xf4, 0x9c, 0x54, 0x7d, 0xb0, 0x70, 0x52, 0x69, 0x9a, 0x7e, 0x49,
	0x66, 0x6e, 0x6a, 0x71, 0x49, 0x62, 0x6e, 0x01, 0x44, 0xa5, 0x94, 0x6e, 0x7a, 0x66, 0x49, 0x46,
	0x69, 0x92, 0x5e, 0x72, 0x7e, 0xae, 0x7e, 0x7a, 0x7e, 0x7a, 0x3e, 0x42, 0x25, 0x88, 0x07, 0x31,
	0x1b, 0xc4, 0x82, 0x28, 0x57, 0xf2, 0xe3, 0x62, 0x77, 0x85, 0x18, 0x2d, 0xe4, 0xcc, 0xc5, 0x93,
	0x5c, 0x5a, 0x54, 0x94, 0x9a, 0x57, 0x12, 0x0f, 0x32, 0x54, 0x82, 0x51, 0x81, 0x51, 0x83, 0xdb,
	0x48, 0x4a, 0x0f, 0x62, 0xa3, 0x1e, 0xcc, 0x1c, 0xbd, 0x10, 0x98, 0x8d, 0x4e, 0x2c, 0x13, 0xee,
	0xcb, 0x33, 0x06, 0x71, 0x43, 0x75, 0x81, 0xc4, 0x95, 0x04, 0xb8, 0xf8, 0xa0, 0xe6, 0x05, 0xa5,
	0x16, 0x96, 0xa6, 0x16, 0x97, 0x28, 0xd9, 0x72, 0xf1, 0xc3, 0x45, 0x8a, 0x0b, 0xf2, 0xf3, 0x8a,
	0x53, 0x85, 0xb4, 0xb8, 0x60, 0xfe, 0x81, 0x5a, 0x22, 0xa0, 0x07, 0xf3, 0x2e, 0x4c, 0x29, 0x4c,
	0x81, 0x51, 0x10, 0xdc, 0xc0, 0xe0, 0xd4, 0xa2, 0xb2, 0xcc, 0xe4, 0x54, 0x21, 0x07, 0x2e, 0x6e,
	0x9f, 0xcc, 0xe2, 0x12, 0x98, 0xb3, 0xc5, 0x31, 0xf4, 0x42, 0x2c, 0x96, 0x92, 0xc0, 0x94, 0x80,
	0xd8, 0x9f, 0xc4, 0x06, 0xf6, 0x8b, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x12, 0x6c, 0x32, 0x73,
	0x6b, 0x01, 0x00, 0x00,
}
