// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/example.proto

package example

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	_ "github.com/gogo/protobuf/types"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for ExampleService service

type ExampleService interface {
	ListExample(ctx context.Context, in *ExampleRequest, opts ...client.CallOption) (*ExampleResponse, error)
}

type exampleService struct {
	c    client.Client
	name string
}

func NewExampleService(name string, c client.Client) ExampleService {
	return &exampleService{
		c:    c,
		name: name,
	}
}

func (c *exampleService) ListExample(ctx context.Context, in *ExampleRequest, opts ...client.CallOption) (*ExampleResponse, error) {
	req := c.c.NewRequest(c.name, "ExampleService.ListExample", in)
	out := new(ExampleResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ExampleService service

type ExampleServiceHandler interface {
	ListExample(context.Context, *ExampleRequest, *ExampleResponse) error
}

func RegisterExampleServiceHandler(s server.Server, hdlr ExampleServiceHandler, opts ...server.HandlerOption) error {
	type exampleService interface {
		ListExample(ctx context.Context, in *ExampleRequest, out *ExampleResponse) error
	}
	type ExampleService struct {
		exampleService
	}
	h := &exampleServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&ExampleService{h}, opts...))
}

type exampleServiceHandler struct {
	ExampleServiceHandler
}

func (h *exampleServiceHandler) ListExample(ctx context.Context, in *ExampleRequest, out *ExampleResponse) error {
	return h.ExampleServiceHandler.ListExample(ctx, in, out)
}
